FROM ubuntu:22.04

MAINTAINER nimmis <kjell.havneskold@gmail.com>

# disable interactive functions
ENV DEBIAN_FRONTEND noninteractive

COPY root/. /

RUN apt update -y 

    # install neede packages
RUN    apt-get install  -y --no-install-recommends ca-certificates && \

    # remove apt cache from image
    apt-get clean all

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/my_init"]
