FROM ubuntu:jammy-20220315

MAINTAINER nimmis <kjell.havneskold@gmail.com>

# disable interactive functions
ENV DEBIAN_FRONTEND noninteractive

COPY root/. /

RUN mkdir -pv /var/cache/apt/archives/partial
RUN mkdir -pv /var/lib/apt/lists/partial
RUN rm -r /var/lib/apt/lists/*

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/my_init"]
