image: nimmis/mtest:22.05
manifests:
  - image: nimmis/mtest:22.05-amd64
    platform:
      architecture: amd64
      os: linux
  - image: nimmis/mtest:22.05-arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: nimmis/mtest:22.05-arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
