#!/bin/bash
# hooks/post_push
# https://docs.docker.com/docker-cloud/builds/advanced/
# https://semver.org/
# https://github.com/ckulka/docker-multi-arch-example/

## requires to be a os/arch combination
DEFAULT_ARCH="linux/amd64"

echo "[***] Downloading manifest-tool-linux-amd64"
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
chmod +x manifest-tool


## add_tag will add a tag and a manifest for each version
function add_tag() {
    echo "[***] Adding tag ${1}"
    docker tag $IMAGE_NAME $DOCKER_REPO:$1
    docker push $DOCKER_REPO:$1

    echo "[---] Running ./manifest-tool push from-args --platforms '${2}' --template '${IMAGE_NAME}_ARCH' --target '${DOCKER_REPO}:${1}'"
    ./manifest-tool push from-args \
        --platforms ${2} \
        --template ${IMAGE_NAME}_ARCH \
        --target ${DOCKER_REPO}:${1}
}


## Push all variant images
## must be done in post_push

MANIFEST=${DOCKERFILE_PATH}-build-manifest
MANIFEST_TAG=$(echo "${IMAGE_NAME}"| cut -d '/' -f2-)

#reset file
echo "image: ${MANIFEST_TAG}" > $MANIFEST
echo "manifests:" >> $MANIFEST

function add_manifest() {
  echo "  - image: ${MANIFEST_TAG}_${1}" >> $MANIFEST
  echo "    platform:" >> $MANIFEST
  echo "      architecture: ${2}" >> $MANIFEST
  echo "      os: linux" >> $MANIFEST
  [[ ! -z "${3}" ]] && echo "      variant: ${3}" >> $MANIFEST
}
for FILE in ${DOCKERFILE_PATH}.*
do
    TARGET_ARCH=$(echo "${FILE}" | cut -d '.' -f 2)

    echo "[---] TARGET_ARCH: ${TARGET_ARCH}"

    ## FUDGE Factor because Docker Hub does not respect "32"
    case "$TARGET_ARCH" in
        *arm32v5)
            BUILD_ARCH="armv5"
            add_manifest armv6 arm v5
            ;;
        *arm32v6)
            BUILD_ARCH="armv6"
            add_manifest armv6 arm v6
            ;;
        *arm32v7)
            BUILD_ARCH="armv7"
            add_manifest armv6 arm v7
        arm64v8)
            BUILD_ARCH="arm64v8"
            add_manifest arm64v8 arm64
            ;;
        *)
            BUILD_ARCH="${TARGET_ARCH}"
            add_manifest arm64v8 arm64
            ;;
    esac

    echo "[---] BUILD_ARCH: ${BUILD_ARCH}"

    docker push ${IMAGE_NAME}_${BUILD_ARCH}
done


echo "[***] Current Build: ${TARGET_TAG}"

MANIFESTFILE="${DOCKERFILE_PATH}-manifest"

echo "[***] updating ./manifest-tool push from-spec ${MANIFEST}"
./manifest-tool push from-spec ${MANIFEST}
exit $?
